const express = require("express");
const router = express.Router();

const authRoutes = require("./auth.route");
const shippingRoutes = require("./shipping.routes");
const userAddressRoutes = require("./userAddress.route");
const productRoutes = require("./product.route");
const cartRoutes = require("./cart.route");
const highlightedCategoryRoutes = require("./highlightedCategory.route");
const orderRoutes = require("./order.routes");
const categoryRoutes = require("./category.route");
const searchRoutes = require("./search.routes");
const sectionClientRoutes = require("./sectionClient.route");
const brandRoutes = require("./brand.route");
const wishlistRoutes = require("./wishlist.routes");
const couponRoutes = require("./coupon.route");
const sliderRoutes = require("./banner.routes");
const reviewRoutes = require("./review.routes");
const flashSaleRoutes = require("./flashSale.routes");
const postRoutes = require("./post.route");
const productViewRoutes = require("./productView.routes");
const productQuestionRoutes = require("./productQuestion.route");
const systemSettingRoutes = require("./systemSetting.routes");
const recommendationRoutes = require("./recommendationRoutes");
const returnRefundRoutes = require("./returnRefundRoutes");
const userPointRoutes = require("./userPoint.Routes");
const membershipRoutes = require("./membership.route.js");
const spinRoutes = require("./spin.route");
const searchImageRoute = require("./searchImage.route");
const chatboxRoutes = require("./chatbox.routes");
const paymentRoutes = require("./payment.routes");
const notificationRoutes = require("./notificationClient.route");

// Payment callbacks
const paymentController = require("../../controllers/client/paymentController");
router.post("/payment/momo-callback", paymentController.momoCallback);
router.get("/payment/momo-callback", paymentController.momoCallback);
router.post("/payment/zalopay-callback", paymentController.zaloCallback);
router.get("/payment/zalopay-callback", paymentController.zaloCallback);
router.post("/payment/vnpay-callback", paymentController.vnpayCallback);
router.get("/payment/vnpay-callback", paymentController.vnpayCallback);

// Route use (KHÔNG ĐỔI PATH, CHỈ XOÁ TRÙNG)
router.use("/", sliderRoutes);
router.use("/tin-noi-bat", postRoutes);
router.use("/", flashSaleRoutes);
router.use("/", searchRoutes);
router.use("/points", userPointRoutes);
router.use("/payment", paymentRoutes);
router.use("/api/client/categories", categoryRoutes);
router.use("/", highlightedCategoryRoutes);
router.use("/orders", orderRoutes);
router.use("/", sectionClientRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/api/client/brands", brandRoutes);
router.use("/", authRoutes);
router.use("/shipping", shippingRoutes);
router.use("/user-address", userAddressRoutes);
router.use("/", productRoutes);
router.use("/", searchImageRoute);
router.use("/chatbox", chatboxRoutes);
router.use("/cart", cartRoutes);
router.use("/system-settings", systemSettingRoutes);
router.use("/review", reviewRoutes);
router.use("/", couponRoutes);
router.use("/notifications", notificationRoutes);
router.use("/product-questions", productQuestionRoutes);
router.use("/spin", spinRoutes);
router.use("/productviews", productViewRoutes);
router.use("/return-refund", returnRefundRoutes);
router.use("/membership", membershipRoutes);
router.use("/recommendations", recommendationRoutes);

module.exports = router;
